<?php

/**
 * Implements hook_migrate_api().
 */
function migrate_dbc_migrate_api() {
  $api = array(
    'api' => 2,
  );
  return $api;
}

/**
 * Implements hook_migrate_overview().
 */
function migrate_dbc_migrate_overview() {
  return t('<p>Listed below are all the migration processes defined for migration
    of our old site to Drupal. Open issues applying to specific migrations
    can be viewed by clicking the migration name. Also, details on how each
    migration will behave when incrementally migrated are provided.</p>
    <p><a href="https://github.com/sanduhrs/dbc/issues">Open migration tickets</a></p>');
}
